# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [231]:
a = 2.0+3.0/5.0
b = (a+10.2)-5.0*2.0
c = a/b+33.8
d = a/(b+c)
e = d*2

print(a)
print(b)
print(c)
print(d)
print(e)

2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) a * 2

c) a + b

d) a / (b * c)

In [232]:
a1 = [[2.0, 3.0, 5.0] + [10, 20, 30]]
a1

[[2.0, 3.0, 5.0, 10, 20, 30]]

In [233]:
b1 = [[2.0, 3.0, 5.0, 10, 20, 30]*2]
b1

[[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]]

In [234]:
c1 = [2.0, 3.0, 5.0, 10, 20, 30] + [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
c1

[2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30]

In [235]:
#d1 = a1 / (b1 * c1)
#d1

#erro = não é possível fazer a multiplicação/divisão entre listas de números não inteiros.

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [236]:
#np.sqrt - não foi possível fazer devido à versão.

obj_simples = [a, b, c, d, e]
obj_quadrado = [obj_simples[i]**0.5 for i in range(len(obj_simples))]


print(obj_quadrado)

[1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]

In [237]:
obj_concat = obj_quadrado + obj_simples
obj_concat

[1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501,
 2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [238]:
valores_array = obj_concat * 2

array_concat = np.array(valores_array)

array_reshape = array_concat.reshape(5, 4)

array_reshape

array([[ 1.61245155,  1.67332005,  5.89309523,  0.26321198],
       [ 0.37223796,  2.6       ,  2.8       , 34.72857143],
       [ 0.06928055,  0.1385611 ,  1.61245155,  1.67332005],
       [ 5.89309523,  0.26321198,  0.37223796,  2.6       ],
       [ 2.8       , 34.72857143,  0.06928055,  0.1385611 ]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [239]:
medias_colunas = np.mean(array_reshape, axis=0)

medias_lista = medias_colunas.tolist()

medias_lista

[2.1494130575327546, 7.8807329122498375, 2.149413057532755, 7.8807329122498375]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [240]:
#obj.shape      sem o ()

total_elementos = array_reshape.shape[0] * array_reshape.shape[1]
print(total_elementos)

20

In [241]:
novo_array = np.vstack([array_reshape, medias_lista])
novo_array

array([[ 1.61245155,  1.67332005,  5.89309523,  0.26321198],
       [ 0.37223796,  2.6       ,  2.8       , 34.72857143],
       [ 0.06928055,  0.1385611 ,  1.61245155,  1.67332005],
       [ 5.89309523,  0.26321198,  0.37223796,  2.6       ],
       [ 2.8       , 34.72857143,  0.06928055,  0.1385611 ],
       [ 2.14941306,  7.88073291,  2.14941306,  7.88073291]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [242]:
#reshape[-1,4]; usa pd para array em df; df.round(3)
novo_novo_array = novo_array.reshape(-1,4)

df_mil_arrays = pd.DataFrame(novo_novo_array)

df_mil_arrays = df_mil_arrays.round(3)

df_mil_arrays

       0       1      2       3
0  1.612   1.673  5.893   0.263
1  0.372   2.600  2.800  34.729
2  0.069   0.139  1.612   1.673
3  5.893   0.263  0.372   2.600
4  2.800  34.729  0.069   0.139
5  2.149   7.881  2.149   7.881

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [243]:
medias = df_mil_arrays.mean(axis=1)

df_mil_arrays['medias'] = medias      

df_mil_arrays

       0       1      2       3    medias
0  1.612   1.673  5.893   0.263   2.36025
1  0.372   2.600  2.800  34.729  10.12525
2  0.069   0.139  1.612   1.673   0.87325
3  5.893   0.263  0.372   2.600   2.28200
4  2.800  34.729  0.069   0.139   9.43425
5  2.149   7.881  2.149   7.881   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [244]:
df_mil_arrays.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
0,6.0,2.149167,2.107787,0.06900,0.682000,1.880500,2.637250,5.89300
1,6.0,7.880833,13.455228,0.13900,0.615500,2.136500,6.560750,34.72900
2,6.0,2.149167,2.107787,0.06900,0.682000,1.880500,2.637250,5.89300
3,6.0,7.880833,13.455228,0.13900,0.615500,2.136500,6.560750,34.72900
medias,6.0,5.015000,3.932315,0.87325,2.301563,3.687625,8.329438,10.12525

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [245]:
df_mil_arrays

       0       1      2       3    medias
0  1.612   1.673  5.893   0.263   2.36025
1  0.372   2.600  2.800  34.729  10.12525
2  0.069   0.139  1.612   1.673   0.87325
3  5.893   0.263  0.372   2.600   2.28200
4  2.800  34.729  0.069   0.139   9.43425
5  2.149   7.881  2.149   7.881   5.01500

In [246]:
df_mil_arrays.columns = ['A', 'B', 'C', 'D', 'medias_linha']

df_mil_arrays.index = ['linha1', 'linha2', 'linha3', 'linha4', 'linha5', 'media_coluna']

df_mil_arrays

                  A       B      C       D  medias_linha
linha1        1.612   1.673  5.893   0.263       2.36025
linha2        0.372   2.600  2.800  34.729      10.12525
linha3        0.069   0.139  1.612   1.673       0.87325
linha4        5.893   0.263  0.372   2.600       2.28200
linha5        2.800  34.729  0.069   0.139       9.43425
media_coluna  2.149   7.881  2.149   7.881       5.01500

In [247]:
medias_cl = df_mil_arrays['medias_linha'].mean()+df_mil_arrays.loc['media_coluna', ['A','B','C','D']].mean()

medias_cl

np.float64(10.030000000000001)

In [ ]:
import numpy as np
import pandas as pd